apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-test
  namespace: argocd
spec:
  project: default


  source:
    repoURL: https://github.com/arieluchka/aks-cluster-project-deployment
    targetRevision: HEAD
    path: prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  
  syncPolicy:
    syncOptions:

    automated:
      selfHeal: true
      prune: true

    