apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-app
  namespace: argocd
spec:
  project: default


  source:
    repoURL: https://github.com/arieluchka/aks-cluster-project-deployment
    targetRevision: feature
    path: staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  
  syncPolicy:
    syncOptions:

    automated:
      selfHeal: true
      prune: true

    