apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubepython
spec:
  selector:
    matchLabels:
      app: kubepython
  replicas: 2
  template:
    metadata:
      labels:
        app: kubepython
    spec:
      containers:
      - name: python-web-test
        image: arieluchka/aks-app-jenkins-test:1.0.1-dev
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

