apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubepython
spec:
  selector:
    matchLabels:
      app: kubepython
  replicas: 2
  template:
    metadata:
      labels:
        app: kubepython
    spec:
      containers:
      - name: python-web-test
        image: arieluchka/kubepython:1.0
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: webconfig
          mountPath: /app/webcode
      volumes:
      - name: webconfig
        configMap:
          name: html-code
